#!/bin/bash
#
# ~/.alias
#

# File permitions
alias chr='chmod 644'
alias chx='chmod 755'
alias mx='chmod a+x'
alias perm='stat --printf "%a %n \n"'

# ls commands
alias l.='ls -d .*'
alias la='ls -lah'
alias ll='ls -lh'
alias lr='ls -lR | less'
alias ls='ls --color=auto'
alias lsl='ls -lah | less'

# Package management
alias lsorphans='sudo pacman -Qdt'
alias rmorphans='sudo pacman -Rs $(pacman -Qtdq)'
alias pacman='sudo pacman'
alias pi='sudo pacman -S'
alias pkgfiles='sudo pacman -Qlq "$1" | grep -v / | xargs du -h | sort -h'
alias pr='sudo pacman -Rs'
alias pu='sudo pacman -Syu'

# File management
alias fhere='find . -name '
alias mkdir='mkdir -pv'

# Process management
alias ps='ps auxf'
alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'

# System management
alias reboot='sudo reboot'
alias mount='mount | column -t'
alias log='journalctl -x'
alias logerr='journalctl -xp err..alert'

# Rebuild package shortcut
alias redwm='cd ~/abs/dwm; updpkgsums; makepkg -fi --noconfirm && killall dwm'

# Handy shortcuts
alias x='exit'
alias ..='cd ..'
alias c='clear'
alias h='history'
alias j='jobs -l'

# Keymap
alias xev='xev | awk -F'\''[ )]+'\'' '\''/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'\'''

# Window properties
alias xprop='xprop | awk '\''
    /^WM_CLASS/{sub(/.* =/, "instance:"); sub(/,/, "\nclass:"); print}
    /^WM_NAME/{sub(/.* =/, "title:"); print}'\'''
