#!/bin/sh
#
# ~/.dwm-status
#

TEMP=$(($(cat /sys/class/thermal/thermal_zone0/temp)/1000))
TIME="$(date '+%a, %-d %b %Y %Z %R')"
USED_RAM=$(free -m | grep '^Mem' | tr -s ' ' | cut -d ' ' -f3)
USED_RAM_H=$(free -h | grep '^Mem' | tr -s ' ' | cut -d ' ' -f3)
TOTAL_RAM=$(free -m | grep '^Mem' | tr -s ' ' | cut -d ' ' -f2)
USED_RAM_PCT=$(perl -e "printf(\"%.f\", $USED_RAM / $TOTAL_RAM * 100)")	# % of Used Memory 
UPTIME=$(uptime | sed 's/.*: //; s/,//g')
VOL=$(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')
BAT=$(acpi -b | sed -r 's/Battery [0-9]+: //' | awk -F ', ' '{if ($1=="Charging") print $2" (+)"; else if ($1=="Discharging") print $2" (-)"; else print $2}')

xsetroot -name "CPU:$UPTIME | RAM:${USED_RAM_H} ${USED_RAM_PCT}% | Temp:${TEMP}C | Vol:$VOL | Bat:$BAT | $TIME"
