#!/bin/sh
#
# ~/.monitor_block_devices
#

pathtoname()
{
  udevadm info -p /sys/"${path:-$1}" | awk -v FS== '/DEVNAME/ {print $2}'
}

stdbuf -oL -- udevadm monitor --udev -s block | while read -r -- _ _ event devpath _; do
  if [ "$event" = add ]; then
    devname=$(pathtoname "$devpath")
    udisksctl mount --block-device "$devname" --no-user-interaction
    mount_point=$(udisksctl info --block-device "$devname" | awk '/MountPoint/ {print $2}')
    [ ! -z "$mount_point" ] && notify-send "Added device!" "Device $devname is mounted to $mount_point!"
  elif [ "$event" = remove ] && [ ! -z "$mount_point" ]; then
    notify-send "Removed device!" "Device ${devname:-N/A} is unmounted!"
  fi
done
