#!/bin/bash
#
# ~/.monitor_android_devices
#

pathtoname()
{
  udevadm info -p /sys/"${path:-$1}" | awk -v FS== '/ID_MODEL=/ {print $2}'
}

stdbuf -oL -- udevadm monitor --udev -t uaccess -t seat | while read -r -- _ _ event devpath _; do
  if [ "$event" = add ]; then
    devname=$(pathtoname "$devpath")
    mount_point=~/${devname}
    [ ! -d "$mount_point" ] && mkdir "$mount_point"
    aft-mtp-mount "$mount_point"
    [ ! -z "$mount_point" ] && notify-send "Added device!" "Device $devname is mounted to $mount_point!"
  elif [ "$event" = remove ] && [ ! -z "$mount_point" ]; then
    notify-send "Removed device!" "Device ${devname:-N/A} is unmounted!"
    fusermount -u "$mount_point"
  fi
done
