#!/bin/sh
#
# ~/.udevadm_monitor
#

pathtoname() {
  udevadm info -p /sys/"$1" | awk -v FS== '/DEVNAME/ {print $2}'
}

stdbuf -oL -- udevadm monitor --udev -s block | while read -r -- _ _ event devpath _; do
  if [ "$event" = add ]; then
    devname=$(pathtoname "$devpath")
    udisksctl mount --block-device "$devname" --no-user-interaction
    notify-send "Added device!" "Device $devname is mounted!"
  elif [ "$event" = remove ]; then
    notify-send "Removed device!" "Device ${devname:-N/A} is unmounted!"
  fi
done
