#!/bin/sh
#
# ~/.xinitrc
#

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  	[ -x "$f" ] && . "$f"
 	done
 	unset f
fi

# Activate NumLock
numlockx &

# Statusbar loop
while true; do
  ~/Projects/dotfiles/dwm/dwm-status
  sleep 1s    # Update every second
done &

# Check threshold system parameter values
while true; do
  # Battery
  BAT=$(acpi -b | awk -F '[,:] ' '{print $3}')

  if (( ${BAT%%%*} <= 15 )); then
    ((! ${is_bat_notif_raised:-0})) && notify-send "Low Battery!" "Please plugin charger!"
    is_bat_notif_raised=1
  else
    is_bat_notif_raised=0
  fi

  sleep 1s    # Check every second
done &

# Monitor and mount block devices
~/Projects/scripts/monitor_block_devices &

# Monitor and mount android devices
~/Projects/scripts/monitor_android_devices &

# Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh) &
export SSH_AUTH_SOCK

# Set wallpaper
feh --no-fehbg --bg-scale ~/Pictures/Wallpapers/Orange-Water-1366x768.jpg &

# Run network-manager applet
nm-applet &

# Run dwm
exec ~/Projects/dotfiles/dwm/startdwm
