#!/bin/sh
#
# ~/.xinitrc
#

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  	[ -x "$f" ] && . "$f"
 	done
 	unset f
fi

# Activate NumLock
numlockx &

# Check threshold system parameter values loop
monitor_low_battery &

# Monitor and mount block devices
monitor_block_devices &

# Monitor and mount android devices
#monitor_android_devices &

# Start the gnome-keyring-daemon
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh) &
export SSH_AUTH_SOCK

# Set wallpaper
~/.fehbg &

# Statusbar loop
# while true; do
#     dwm-status
#     sleep 1s
# done &

# Run slstatus as alternative to bash dwm-status
slstatus &

# Screensaver manager
xss-lock -- i3lock -n -i ~/.lock_screen &

# Run applets
nm-applet &
volumeicon &
#xinput --set-prop 12 --type=float 'libinput Accel Speed' 0.50  # Set A4TECH USB mouse acceleration
xinput --set-prop 11 --type=float 'libinput Accel Speed' -0.85  # Set MOSART Semi. 2.4G Wireless Mouse

# Solve a rendering issue of Java GUIs
wmname LG3D &

# Start compositor
compton --config ~/.compton.conf -b

# Run dwm
exec startdwm
#exec bspwm -c ~/.bspwmrc

