#!/bin/bash

while true; do
  date                # output goes to the title window
  date                # output goes to the title window
  date                # output goes to the title window
  #dmesg | tail -n 10  # output goes to the slave window
  sleep 1
done | dzen2 -l 2 -u
