#!/bin/sh
#
# ~/.dmenu_run
# 
# Change /usr/bin/dmenu_run to run this file and exit
# Run terminal applications within terminal, others - in standard manner

TERM_APPS=~/Projects/dotfiles/dmenu/dmenu_term_apps
FILTER_APPS=~/Projects/dotfiles/dmenu/dmenu_filter_apps

app=$(dmenu_path | grep -f "$FILTER_APPS" | dmenu "$@")

echo "$app" | grep -f "$TERM_APPS" && st -e "$app" || echo "$app" | ${SHELL:-"/bin/sh"} &
